ARGUMENT_CONFIG_FILE = 'config-file'

CONF_SEC_WATCH      = 'watch'
CONF_SEC_GENERAL    = 'general'
CONF_ITEM_DIRECTORY = 'directory'
CONF_ITEM_RECURSIVE = 'recursive'

LOG_CRITICAL = 50
LOG_ERROR = 40
LOG_WARNING = 30
LOG_INFO = 20
LOG_DEBUG = 10
LOG_NOTSET = 0

LOGTO_SYSLOG = 1
LOGTO_FILELOG = 2